export const ADD_ENTRIES     = 'ADD_ENTRIES'
export const RECEIVE_ENTRIES = 'RECEIVE_ENTRIES'
export const SELECT_MONTH    = 'SELECT_MONTH'
export const HILIGHT_ENTRIES = 'HILIGHT_ENTRIES'
export const UPDATE_ENTRY    = 'UPDATE_ENTRY'

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const ADD_CATEGORY       = 'ADD_CATEGORY'

export const RECEIVE_BUDGET          = 'RECEIVE_BUDGET'
export const SET_BUDGET_FOR_CATEGORY = 'SET_BUDGET_FOR_CATEGORY'